# Generated by Django 5.1.7 on 2025-04-15 21:52

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Тег должен быть не короче 2 символов')], verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Заголовок должен быть не короче 5 символов')], verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Обложка статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание статьи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновление статьи')),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='news', to='news.tag')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='news_news_created_33ef44_idx')],
            },
        ),
    ]
