# Generated by Django 5.1.7 on 2025-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='cache',
            field=models.FileField(default=1, upload_to='uploads_model', verbose_name='Cache'),
            preserve_default=False,
        ),
    ]
