# Generated by Django 5.1.7 on 2025-04-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_launcher_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория правил',
                'verbose_name_plural': 'Категории правил',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок правила')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='landing_page.rulecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст подпункта')),
                ('punishment', models.TextField(blank=True, verbose_name='Наказание за нарушение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landing_page.rule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Подпункт правила',
                'verbose_name_plural': 'Подпункты правил',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RuleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание исключения')),
                ('condition', models.TextField(blank=True, verbose_name='Условия применения')),
                ('rule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='landing_page.ruleitem', verbose_name='Подпункт правила')),
            ],
            options={
                'verbose_name': 'Исключение',
                'verbose_name_plural': 'Исключения',
            },
        ),
    ]
