# Generated by Django 5.1.7 on 2025-04-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_rulecategory_rule_ruleitem_ruleexception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ruleitem',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='ruleexception',
            name='rule_item',
        ),
        migrations.DeleteModel(
            name='RuleCategory',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='RuleException',
        ),
        migrations.DeleteModel(
            name='RuleItem',
        ),
    ]
