# Generated by Django 5.1.7 on 2025-04-13 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_remove_rule_category_remove_ruleitem_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rules', models.CharField(max_length=160, verbose_name='Название правил')),
                ('rules_description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
